mainpage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

homepage:
    path: /homepage
    defaults:
      _controller: AppBundle:Default:index

game:
    path: /game
    defaults:
      _controller: AppBundle:Default:index

rules:
    path: /rules
    defaults:
      _controller: AppBundle:Default:index

register:
    path: /register
    defaults:
      _controller: AppBundle:Default:index

login:
    path: /login
    defaults:
      _controller: AppBundle:Default:index

api_user_list:
    path: /api/user/list
    defaults:
      _controller: AppBundle:Api:userList
    methods:  [GET]

api_user_create:
    path: /api/user/create
    defaults:
      _controller: AppBundle:Api:userCreate
    methods:  [POST]
